flaskr/views.py
# views.py
from datetime import datetime
from flask import (
  Blueprint, abort, request, render_template,
  redirect, url_for, flash, session, jsonify
)
from flask_login import login_user, login_required, logout_user, current_user
from flaskr.models import User, PasswordResetToken, UserConnect, TalkMessage, UserContact
from flaskr import db

from flaskr.forms import (
  LoginForm, RegisterForm, ResetPasswordForm, ForgotPasswordForm,
  UserForm, ChangePasswordForm, UserSearchForm, ConnectForm, MessageForm,
  ContactForm
)
from flask_mail import Mail, Message
from flaskr.utils.message_format import make_message_format, make_old_message_format

bp = Blueprint('app', __name__, url_prefix='')
mail = Mail()

@bp.route('/')
def home():
  """
  ホーム画面を表示するルート関数。

  Returns:
    HTML: ホーム画面のHTMLテンプレート。
  """
  friends = requested_friends = requesting_friends = None
  connect_form = ConnectForm()
  session['url'] = 'app.home'
  if current_user.is_authenticated:
    friends = User.select_friends()
    requested_friends = User.select_requested_friends()
    requesting_friends = User.select_requesting_friends()
  return render_template(
    'home.html', 
    friends = friends,
    requested_friends = requested_friends,
    requesting_friends = requesting_friends,
    connect_form = connect_form
  )

@bp.route('/logout')
def logout():
  """
  ログアウトを処理するルート関数。

  Returns:
    redirect: ログアウト後にホーム画面にリダイレクトする。
  """
  logout_user() # ログアウト実行
  return redirect(url_for('app.home')) # ログアウトしたらホーム画面へ

@bp.route('/login', methods=['GET', 'POST'])
def login():
  """
  ログインを処理するルート関数。

  Returns:
    HTML: ログイン画面のHTMLテンプレート。
  """
  form = LoginForm(request.form)
  if request.method == 'POST' and form.validate():
    # フォームから入力されたメールアドレスに一致するユーザーをデータベースから取得
    user = User.select_user_by_email(form.email.data)
    # ユーザーが存在し、アクティブであり、かつパスワードが正しい場合
    if user and user.is_active and user.validate_password(form.password.data):
      login_user(user, remember=True) # ユーザーをログイン状態にし、セッションに保存
      next_url = request.args.get('next', url_for('app.home'))
      # ログイン成功後に指定されたリダイレクト先URLにリダイレクト
      return redirect(next_url)
    elif not user: # ユーザーが存在しない場合
      flash('このユーザーは存在しません')
    elif not user.is_active: # ユーザーが存在するが無効な場合
      flash('無効なユーザーです。パスワードを再設定してください。')
    elif not user.validate_password(form.password.data):
      # ユーザーが存在し、アクティブであるが、パスワードが間違っている場合
      flash(f'パスワードが間違っているよ。もう一度入力してみて！<br>もし忘れたら下のリンクからパスワードの再設定してね')
  # ログインが失敗したか、GETリクエストの場合はログイン画面を表示
  return render_template('login.html', form=form)

@bp.route('/register', methods=["GET", "POST"])
def register():
  """
  新しいユーザーを登録し、パスワードリセット用のトークンを生成してメールを送信します。

  このメソッドは新しいユーザーを登録し、パスワードリセットトークンを生成する。
  ユーザーに対しトークンを含むメールを送信します。
  メールにはパスワードリセット用のURLが含まれており、
  クリックすることで、パスワードをリセットできるようになります。

  Args:
    self: インスタンス自体。
  
  Returns:
    flask.Response: ユーザーに通知を表示するためのリダイレクトレスポンス。
  """
  form = RegisterForm(request.form) # インスタンスを作成
  if request.method == 'POST' and form.validate(): # POSTメソッドかつバリデーション成功
    # formデータを利用して新規ユーザーを作成
    user = User(
      username = form.username.data,
      email = form.email.data
    )
    with db.session.begin(nested=True):
      # DBに新規ユーザーを登録
      user.create_new_user()
    db.session.commit()
    # パスワードリセットトークンを生成
    with db.session.begin(nested=True):
      token = PasswordResetToken.publish_token(user)
    db.session.commit()
    email = user.email
    # パスワード設定用URLをメールで送信
    PasswordResetToken.send_password_reset_email(email, token)
    
    flash('パスワード設定用URLをお送りします。ご確認をお願いします。')
    
  # バリデーションが失敗した場合、register.htmlを再度表示
  return render_template('register.html', form=form)

@bp.route('/reset_password/<uuid:token>', methods=['GET', 'POST'])
def reset_password(token):
  """
  パスワードリセットを処理するルート関数。

  Args:
    token (uuid): パスワードリセットのトークン。

  Returns:
    HTML: パスワードリセット画面のHTMLテンプレート。
  """
  form = ResetPasswordForm(request.form)
  # PasswordResetTokenクラスのトークンからユーザーidを取得
  reset_user_id = PasswordResetToken.get_user_id_by_token(token)
  if not reset_user_id:
    abort(500) # 存在しない場合はHTTPステータスコードの500を返す
  if request.method == 'POST' and form.validate():
    password = form.password.data # 新しいパスワードの取得
    user = User.select_user_by_id(reset_user_id) # DBから対応するユーザーを取得
    # トランザクション内でDBとのセッションを開始
    with db.session.begin(nested=True):
      user.save_new_password(password) # 新しいパスワードをユーザーオブジェクトに保存
      PasswordResetToken.delete_token(token) # トークンを使用して関連するパスワードリセットトークンを削除
    db.session.commit()
      
    flash('パスワードを更新しました')
    
    return redirect(url_for('app.login'))
  return render_template('reset_password.html', form=form)

@bp.route('/forgot_password', methods=['GET', 'POST'])
def forgot_password():
  """
  パスワードを忘れた場合の処理をするエンドポイント。

  ユーザーがパスワードを忘れた場合、ここを通じてパスワードリセットの手続きを行います。
  メールアドレスがフォームに入力され、存在するユーザーであれば、
  パスワードリセット用のトークンを生成し、ユーザーにメールで送信します。

  Args: None

  Returns:
  flask.Response: フォームの入力結果や処理結果に基づいたレスポンス。
  """
  # ForgotPasswordForm インスタンスの作成
  form = ForgotPasswordForm(request.form)
  if request.method == 'POST' and form.validate(): # POSTメソッドかつバリデーション成功
    email = form.email.data # フォームから入力されたメールアドレスを取得
    # 入力されたメールアドレスに対応するユーザーをDBから取得
    user = User.select_user_by_email(email)
    if user: # userが存在
      # パスワードリセットトークンを生成し、DBに保存
      with db.session.begin(nested=True):
        token = PasswordResetToken.publish_token(user)
      db.session.commit()
      
      # パスワードリセット用のメールをユーザーに送信
      PasswordResetToken.send_password_reset_email(email, token)
      
      flash(f'パスワード再設定用のURLをメールでお送りしました。\nリンク先より再設定をお願いします。')
      # ユーザーが存在しない場合
    else:
      flash('このメールアドレスのユーザーは存在しません')
  
  return render_template('forgot_password.html', form=form)

@bp.route('/user', methods=['GET', 'POST'])
@login_required
def user():
  """
  ユーザー情報編集を処理します。

  このルートは、ログイン済みユーザーが自分のユーザーページにアクセスし、ユーザー情報を表示および更新できるようにします。

  Args: None

  Returns:
    リクエストメソッドがGETなら:
      'user.html'テンプレートを描画し、ユーザーの情報を表示するためのUserFormを提供します。

    リクエストメソッドがPOSTでフォームが有効な場合:
      ログイン中のユーザーのIDを取得します。
      Userクラスの'select_user_by_id'メソッドを使用して、ユーザーIDに対応するユーザーを取得します。
      トランザクション内でユーザーのユーザー名とメールを更新します。
      フォームからアップロードされたユーザーのプロフィール画像を保存し、画像のパスをユーザーオブジェクトに設定します。
      データベースセッションをコミットし、フラッシュメッセージを表示します。

  Note:
    このルートはユーザーがログインしていることを要求します（@login_requiredでデコレートされています）。
  """
  form = UserForm(request.form)
  if request.method == 'POST' and form.validate():
    user_id = current_user.get_id()
    user = User.select_user_by_id(user_id)
    with db.session.begin(nested=True):
      user.username = form.username.data
      user.email = form.email.data
      file = request.files[form.picture_path.name].read()
      if file:
        file_name = user_id + ' ' + \
          str(int(datetime.now().timestamp())) + '.jpg'
        picture_path = 'flaskr/static/user_image/' + file_name
        open(picture_path, 'wb').write(file)
        user.picture_path = 'user_image/' + file_name
    db.session.commit()
    flash('ユーザー情報を更新しました')
  return render_template('user.html', form=form)

@bp.route('/change_password', methods=['GET', 'POST'])
@login_required
def change_password():
  """
  パスワード変更ページを処理します。

  このルートは、ログイン済みユーザーが自分のアカウントのパスワードを変更できるようにします。

  Args: None

  Returns:
    リクエストメソッドがGETなら:
      'change_password.html'テンプレートを描画し、パスワード変更用のChangePasswordFormを提供します。

      リクエストメソッドがPOSTでフォームが有効な場合:
        ログイン中のユーザーのIDを使用してユーザーオブジェクトを取得します。
        フォームから新しいパスワードを取得します。
        トランザクション内でユーザーオブジェクトに新しいパスワードを保存します。
        データベースセッションをコミットし、フラッシュメッセージを表示します。
        ユーザーのアカウントページにリダイレクトします。

  Note:
    このルートはユーザーがログインしていることを要求します（@login_requiredでデコレートされています）。

  Example:
    フォームを使用してパスワードを変更し、データベースにコミットすると、フラッシュメッセージが表示され、
    ユーザーはuser.htmlにリダイレクトされます。
  """
  form = ChangePasswordForm(request.form)
  if request.method == 'POST' and form.validate():
    user = User.select_user_by_id(current_user.get_id())
    password = form.password.data # 新しいパスワードの取得
    with db.session.begin(nested=True):
      user.save_new_password(password) # 新しいパスワードをユーザーオブジェクトに保存
    db.session.commit()
    flash('パスワードの更新を行いました')
    return redirect(url_for('app.user'))
  return render_template('change_password.html', form=form)

@bp.route('/user_search', methods=['GET'])
@login_required
def user_search():
  """
  ユーザー検索機能

  ログイン済みのユーザーがユーザー名で他のユーザーを検索できる。

  Args: None

  Returns:
    リクエストメソッドがGETなら:
      'user_search.html'テンプレートを描画し、入力用のUserSearchFormを提供します。

    リクエストメソッドがPOSTでフォームが有効な場合:
      提出されたフォームデータからユーザー名を取得します。
      Userクラスの'search_by_name'メソッドを呼び出して、提供されたユーザー名に一致するユーザーを取得します。
      'user_search.html'テンプレートを描画し、UserSearchFormと一致するユーザーのリストを提供します。

  Note:
    このルートはユーザーがログインしていることを要求します（@login_requiredでデコレートされています）。
  """
  form = UserSearchForm(request.form)
  connect_form = ConnectForm()
  session['url'] = 'app.user_search'
  users = None
  user_name = request.args.get('username', None, type=str)
  next_url = prev_url = None
  if user_name:
    page = request.args.get('page', 1, type=int)
    posts = User.search_by_name(user_name, page)
    next_url = url_for('app.user_search', page=posts.next_num, username=user_name) if posts.has_next else None
    prev_url = url_for('app.user_search', page=posts.prev_num, username=user_name) if posts.has_prev else None
    users = posts.items
    # UserテーブルとUserConnectテーブルを紐付け、statusを確認する
    # from 自分のID, to 相手のID, status=1:自分から申請中
    # to 自分のID, from 相手のID, status=1:相手から申請中
    # status=2:フレンド登録済み
    # レコードが存在しない場合はどちらでない
  return render_template(
    'user_search.html', form=form, connect_form=connect_form,
    users=users, next_url=next_url, prev_url=prev_url
  )

@bp.route('/connect_user', methods=['POST'])
@login_required
def connect_user():
  """
  ユーザー接続の処理を行う関数。

  ユーザー接続フォームからのPOSTリクエストを処理し、友達の接続やリクエストの受諾を行います。

  Returns:
    redirect: ユーザーを指定されたURLにリダイレクトします。
  """
  form = ConnectForm(request.form)
  if request.method == 'POST' and form.validate():
    if form.connect_condition.data == 'connect':
      new_connect = UserConnect(current_user.get_id(), form.to_user_id.data)

flaskr/templates/_formhelpers.html
{# _formhelpers.html #}
{% macro render_field(field)%}
<dt>
  {{ field.label }}
  <dd>
    {{ field(**kwargs) | safe }}
    {% if field.errors %}
    <ul class="errors">
      {% for error in field.errors %}
      <li>{{ error }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </dd>
</dt>
{% endmacro %}

flaskr/templates/change_password.html
{# change_password.html #}
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード変更 - {{ super() }}
{% endblock %}
{% block content %}
<h1>パスワード変更</h1>
<div class="row">
  <form method="POST">
    {{ form.csrf_token }}
    <p>パスワードは10文字以上で入力してください</p>
    {{ render_field(form.password) }}
    {{ render_field(form.confirm_password) }}
    {{ form.submit() }}

    {# パスワードの要件に違反した場合のエラーメッセージを表示 #}
    {% if form.errors %}
      <ul class="errors">
        {% for error in form.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </form>
</div>
{% endblock %}

flaskr/templates/connect_list.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-4">
  <h2>ユーザーコネクト削除用</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">from_user_id</th>
        <th scope="col">to_user_id</th>
        <th scope="col">status</th>
      </tr>
    </thead>
    <tbody>
      {% for connect in connects %}
      <tr>
        <th scope="row">{{ connect.id }}</th>
        <td>{{ connect.from_user_id }}</td>
        <td>{{ connect.to_user_id }}</td>
        <td>{{ connect.status }}</td>
        <td>
          <form action="{{ url_for('app.connect_delete', id=connect.id) }}" method="POST">
            <input class="btn btn-danger btn-sm" type="submit" value="削除">
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

flaskr/templates/contact.html
{# contact.html #}
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
contact - {{ super() }}
{% endblock %}
{% block content %}
<h1 class="text-primary" style="text-align: center;">お問い合わせ</h1>
<div class="row">
  <form method="POST" style="border: thick double #3498db;
    border-radius: 20px; padding: 40px; margin: 20px auto; max-width: fit-content">
    {{ form.csrf_token }}
    {{ render_field(form.body) }}
    {{ form.submit(class="my-2") }}
  </form>
</div>
{% endblock %}

flaskr/templates/forgot_password.html
{# forgot_password.html #}
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワード再設定 - {{ super() }}
{% endblock %}
{% block content %}
<div class="row">
  <h1>パスワード再設定画面</h1>
  <form method="POST">
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    {{ form.submit() }}
  </form>
</div>
{% for message in get_flashed_messages() %}
<div class="alert alert-info" role="alert">
  {{ message }}
</div>
{% endfor %}
{% endblock %}

flaskr/templates/home.html
{# home.html #}
{% extends "base.html" %}
{% block title %}
ちゃプリ home {{ super() }}
{% endblock title %}
{% block content %}
<div class="row">
  {% if current_user.is_authenticated %}
  <div class="col-lg-4 offset-lg-2">
    {% if current_user.picture_path %}
      <img src="{{ url_for('static', filename=current_user.picture_path) }}"
      class="img-fluid" alt="User Picture">
    {% endif %}
  </div>
  <div class="col-lg-4">
    <p>ユーザー名：{{ current_user.username }}</p>
    <p>メールアドレス：{{ current_user.email }}</p>
  </div>
  {% for message in get_flashed_messages() %}
  <div class="alert alert-info" role="alert">
  {{ message }}
  </div>
  {% endfor %}
  <div class="container mt-4">
    <table class="table table-striped caption-top table-bordered border-primary">
      <caption class="bg-info text-white fw-bold text-center fs-2">フレンドリスト</caption>
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">プロフィール画像</th>
          <th scope="col">ユーザー名</th>
          <th scope="col">メッセージ</th>
        </tr>
      </thead>
      <tbody>
      {% for friend in friends %}
        <tr>
          <td>{{ loop.index }}</td>
          {% if friend.picture_path %}
          {% set img_src = url_for('static', filename=friend.picture_path) %}
          <td><img class="img-fluid" src="{{ img_src }}" alt="{{ friend.username }}" style="max-width: 100px; max-height: 100px;"></td>
          {% else %}
          <td></td>
          {% endif %}
          <td>{{ friend.username }}</td>
          <td><a href="{{ url_for('app.message', id=friend.id) }}" class="btn btn-link">メッセージ送信</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="container mt-4">
    <table class="table table-striped caption-top table-bordered border-primary">
      <caption class="bg-info text-white fw-bold text-center fs-2">届いた申請リスト</caption>
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">プロフィール画像</th>
          <th scope="col">ユーザー名</th>
          <th scope="col">フレンド承認状況</th>
        </tr>
      </thead>
      <tbody>
      {% for friend in requested_friends %}
      <tr>
        <td>{{ loop.index }}</td>
        {% if friend.picture_path %}
        {% set img_src = url_for('static', filename=friend.picture_path) %}
        <td><img class="img-fluid" src="{{ img_src }}" alt="{{ friend.username }}" style="max-width: 100px; max-height: 100px;"></td>
        {% else %}
        <td></td>
        {% endif %}
        <td>{{ friend.username }}</td>
        <td>
          <form method="POST" action="{{ url_for('app.connect_user')}}">
            {{ connect_form.csrf_token }}
            {{ connect_form.connect_condition(value='accept') }}
            {{ connect_form.to_user_id(value=friend.id) }}
            {{ connect_form.submit(class="btn btn-primary", value='申請承認') }}
          </form>
        </td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="container mt-4">
    <table class="table table-striped caption-top table-bordered border-primary">
    <caption class="bg-info text-white fw-bold text-center fs-2">申請済みリスト</caption>
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">プロフィール画像</th>
          <th scope="col">ユーザー名</th>
        </tr>
      </thead>
      <tbody>
      {% for friend in requesting_friends %}
      <tr>
        <td>{{ loop.index }}</td>
        {% if friend.picture_path %}
        {% set img_src = url_for('static', filename=friend.picture_path) %}
        <td><img class="img-fluid" src="{{ img_src }}" alt="{{ friend.username }}" style="max-width: 100px; max-height: 100px;"></td>
        {% else %}
        <td></td>
        {% endif %}
        <td>{{ friend.username }}</td>
      </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  
  {% else %}
  <div class="text-center" style="padding: 20px;">
    <h3>1 on 1 のチャットアプリ</h3>
    <h1 style="color:#622d18; text-shadow:0 0 15px #dbea06fe;" class="fs-1"><b>ちゃプリ</b></h1>
    <img class="images" src="{{ url_for('static', filename='images/kids_yarn_phone.png') }}" alt="糸電話の画像">
    <p class="text-secondary fs-5">
    <a href="{{url_for('app.login')}}">ログイン</a> or 
    <a href="{{url_for('app.register')}}">新規登録</a> をお願いします
    </p>
    <p class="text-warning fs-5">※ メニューからもえらべるよ</p>
    <p class="text-danger">
    ※ ことばづかいに気をつけようね。お友達を傷つけるようなことは言わないこと。<br>
    みんなのおやくそくだよ！！！！！！！！    by さくしゃ
    </p>
  </div>
  {% endif %}
</div>
{% endblock %}

flaskr/templates/login.html
{# login.html #}
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ログイン - {{ super() }}
{% endblock %}
{% block content %}
<h1 class="text-primary" style="text-align: center;">ログインはここ!</h1>
{% for message in get_flashed_messages() %}
<div class="alert alert-info" role="alert">
  {{ message | safe }}
</div>
{% endfor %}
<div class="row">
  <form method="POST" style="border: thick double #3498db;
    border-radius: 20px; padding: 40px; margin: 20px auto; max-width: fit-content">
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    {{ form.submit(class="my-2") }}
  </form>
  <a href="{{ url_for('app.forgot_password') }}">
  パスワードをお忘れですか？
  </a>
</div>
{% endblock %}

flaskr/templates/register.html
{# register.html #}
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
新規ユーザー登録 - {{ super() }}
{% endblock %}
{% block content %}
<h1 class="text-primary" style="text-align: center;">新規登録!!!!!!!!</h1>
<h2 class="text-success" style="text-align: center;">ちゃプリへようこそ！</h2>
<div class="row">
  <form method="POST" style="border: thick double #3498db;
    border-radius: 20px; padding: 40px; margin: 20px auto; max-width: fit-content">
    {{ form.csrf_token }}
    {{ render_field(form.username) }}
    {{ render_field(form.email) }}
    {{ form.submit(class="my-2") }}
  </form>
  {% for message in get_flashed_messages() %}
    <div class="alert alert-info" role="alert">
    {{ message }}
    </div>
  {% endfor %}
  <div class="row mt-3">
  <p>既にアカウントをお持ちですか？ <a href="{{ url_for('app.login') }}">ログインはこちらから</a></p>
  </div>
</div>
{% endblock %}

flaskr/templates/reset_password.html
{# reset_password.html #}
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
パスワードリセット - {{ super() }}
{% endblock %}
{% block content %}
<h1 class="text-primary" style="text-align: center;">パスワード設定</h1>
<div class="row">
  <form method="POST" style="border: thick double #3498db;
    border-radius: 20px; padding: 40px; margin: 20px auto; max-width: fit-content">
    {{ form.csrf_token }}
    <p class="text-warning fs-5">パスワードは10文字以上だよ！</p>
    {{ render_field(form.password) }}
    {{ render_field(form.confirm_password) }}
    {{ form.submit(class="my-2") }}

    {# パスワードの要件に違反した場合のエラーメッセージを表示 #}
    {% if form.errors %}
      <ul class="errors">
        {% for error in form.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </form>
</div>
{% endblock %}

flaskr/templates/user.html
{# user.html #}
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー情報編集 - {{ super() }}
{% endblock %}
{% block content %}
<div class="text-primary" style="text-align: center;">
<h1>{{ current_user.username }}さんのプロフィール</h1>
</div>
<div class="row">
  {% for message in get_flashed_messages() %}
  <div class="alert alert-info" role="alert">
  {{ message }}
  </div>
  {% endfor %}
  <div class="col-6">
    {% if current_user.picture_path %}
    <img src="{{ url_for('static', filename=current_user.picture_path)}}"
    class="img-fluid" alt="User Picture">
    {% endif %}
  </div>
  <div class="col-6">
    <form method="POST" enctype="multipart/form-data" style="border: thick double #3498db;
    border-radius: 20px; padding: 40px; margin: 20px auto; max-width: fit-content">
      {{ form.csrf_token }}
      {{ render_field(form.username, value=current_user.username) }}
      {{ render_field(form.email, value=current_user.email) }}
      {{ render_field(form.picture_path) }}
      {{ form.submit(class="my-2") }}
    </form>
    <a href="{{ url_for('app.change_password') }}">パスワード変更はこちらから</a>
  </div>
</div>
{% endblock %}

flaskr/templates/user_search.html
{% from "_formhelpers.html" import render_field %}
{% extends "base.html" %}
{% block title %}
ユーザー検索 - {{ super() }}
{% endblock %}
{% block content %}
{# <div class="container"> #}
<div class="text-primary" style="text-align: center;">
  <h1>お友達検索</h1>
  <p>ユーザー名を入力し、お友達を探してみよう！</p>
</div>
{# </div> #}
<div class="row">
  <div class="col-4 offset-2">
    <img class="img-fluid" src="{{ url_for('static', filename='images/magnifier_animal_inu.png') }}" alt="探偵ドッグ">
  </div>
  <div class="col-6">
    <form method="GET" style="border: thick double #3498db;
    border-radius: 20px; padding: 40px; margin: 20px auto; max-width: fit-content">
      {{ form.csrf_token }}
      {{ render_field(form.username) }}
      {{ form.submit(class="my-2") }}
    </form>
  </div>
  <div class="col-lg-12">
    {% if users %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">プロフィール画像</th>
          <th scope="col">ユーザー名</th>
          <th scope="col">フレンド申請or承認</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <th scope="col">{{ loop.index }}</th>
          {% if user.picture_path %}
          <th scope="col">
            {% set img_src = url_for('static', filename=user.picture_path) %}
            <img class="img-fluid" src="{{ img_src }}" alt="{{ user.username }}" style="max-width: 100px; max-height: 100px;">
          </th>
          {% else %}
          <th scope="col"></th>
          {% endif %}
          <th scope="col">{{ user.username }}</th>
          <th scope="col">
            {% if user.joined_status_from_to == 2 or user.joined_status_to_from == 2 %}
            フレンド
            {% elif user.joined_status_from_to == 1 %}
            フレンド申請中
            {% elif user.joined_status_to_from == 1 %}
            <form method="POST" action="{{ url_for('app.connect_user') }}">
              {{ connect_form.csrf_token }}
              {{ connect_form.connect_condition(value='accept') }}
              {{ connect_form.to_user_id(value=user.id) }}
              {{ connect_form.submit(class='btn btn-primary', value='フレンド承認')}}
            </form>
            {% else %}
            <form method="POST" action="{{ url_for('app.connect_user') }}">
              {{ connect_form.csrf_token }}
              {{ connect_form.connect_condition(value='connect') }}
              {{ connect_form.to_user_id(value=user.id) }}
              {{ connect_form.submit(class='btn btn-primary', value='フレンド申請する')}}
            </form>
            {% endif %}
          </th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if prev_url %}
      <a href="{{ prev_url }}">前へ</a>
    {% endif %}
    {% if next_url %}
      <a href="{{ next_url }}">次へ</a>
    {% endif %}
    {% else %}
      {% for message in get_flashed_messages() %}
      <div class="alert alert-warning" role="alert">
      {{ message }}
      </div>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock %}